name: CI Testing Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=password" >> .env
        echo "POSTGRES_DB=securenote_db" >> .env
        echo "SECRET_KEY=testing_secret_key_123456789" >> .env
        
        # Random Fernet secret key for tests
        echo "ENCRYPTION_KEY=v_p93ve5y-J5X8Q7Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Y=" >> .env
        
        echo "REDIS_HOST=redis" >> .env
        echo "REDIS_PORT=6379" >> .env

    - name: Start containers
      run: docker compose up -d --build

    - name: Wait for DB
      run: sleep 10

    - name: Run Migrations
      run: docker compose exec -T web alembic upgrade head

    - name: Run Tests
      run: docker compose exec -T web python -m pytest